### ISSUE TITLE
Not working with touch

### ISSUE THREAD

**Issue by johannb75** [arch-inc/fabricjs-psbrush#20] opened 2021-05-13 12:55 UTC
Hi. I really appreciate the effort you put into this library.
On my iPad Pro, it works perfectly with the stylus but when using touch, the line is really thin (even if I set brush width to 100).
Here is a screenshot:
![image](https://user-images.githubusercontent.com/67163473/118128364-137c2b80-b3fb-11eb-8701-15ea9d8c1fb3.png)
I have no idea why it does that because on my Surface Pro, it works perfectly with touch.
Maybe instead of using the native API, you can use a library such as [pressure.js](https://pressurejs.com/documentation.html) which has a polyfill when pressure is not available and uses time (even though I don't think it's adapted for this use case)
Thanks !

Might help:
https://developer.apple.com/forums/thread/31124

**Comment by johannb75** [comment] 2021-06-20 17:22
@arcatdmz Any update on this issue ?

**Comment by arcatdmz** [comment] 2021-09-22 10:27
@johannb75 I believe the issue is fixed with v0.0.18! Please feel free to re-open if you think the issue persists.

**Closed by arcatdmz** 2021-09-22 10:27 UTC
